AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for Tapestry AI Data Ingestion

Resources:
  TapestryPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::<your-account-id>:role/CodePipelineRole
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: <your-github-user>
                Repo: tapestry-ai-data-ingestion
                Branch: main
                OAuthToken: <your-github-oauth-token>
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: tapestry-ai-data-ingestion-codebuild
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: '1'
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ClusterName: <your-ecs-cluster>
                ServiceName: <your-ecs-service>
                FileName: ecs-task-def.json
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: <your-codepipeline-artifact-bucket>
